Update and rename recipes/neofetch/build to recipes/app-misc/neofetch/build

diff --git a/recipes/app-misc/neofetch/build b/recipes/app-misc/neofetch/build
--- a/recipes/app-misc/neofetch/build
+++ b/recipes/app-misc/neofetch/build
@@ -2,9 +2,9 @@
 set -e
 
 echo "Downloading Neofetch 7.1.0 source..."
-
 wget -q https://github.com/dylanaraps/neofetch/archive/7.1.0.tar.gz -O neofetch-7.1.0.tar.gz
+echo "Extracting Neofetch and changing dir..."
 tar xf neofetch-7.1.0.tar.gz
 cd neofetch-7.1.0
 
-[ -f "neofetch" ] || err "Neofetch script not found after extraction"
+[ -f "neofetch" ] || err "Neofetch not found after extraction"
